GRANT CREATE PUBLIC SYNONYM TO pokemon_pokepaste;
GRANT CREATE VIEW TO pokemon_pokepaste;
--
CREATE USER USUARIO_POKEMON_PASTE IDENTIFIED BY "Contrasena.123"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO USUARIO_POKEMON_PASTE;

GRANT ALL ON pokemon_pokepaste.pokemon_paste TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.move TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.move_cat TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.gender TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.item TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.pkmn_ability TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.ability TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.nature TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.pokemon_type_combination TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.pokemon_type TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.pokemon TO USUARIO_POKEMON_PASTE;

GRANT CREATE VIEW TO USUARIO_POKEMON_PASTE;

GRANT SELECT ON pokemon_pokepaste.V_GET_PKMN TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.V_GET_MOVES TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.V_GET_ITEMS TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.V_GET_ABILITIES TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.V_GET_PKMN_TYPES TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.V_GET_NATURES TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.V_GET_POKEPASTE TO USUARIO_POKEMON_PASTE;
GRANT SELECT ON pokemon_pokepaste.V_GET_MOVE_TABLE TO USUARIO_POKEMON_PASTE;



